CREATE OR REPLACE VIEW ORDER_PROCESS.ORDER_XFRM.V_INVOICE AS
SELECT ORDER_ID,
    ORDER_DATE,
    INVOICE_DATE,
    TAX_AMOUNT,
    TOTAL_AMOUNT,
    DISCOUNT,
    FINAL_INVOICE_AMT,
    CUSTOMER_ID,
    CREATE_DATE,
    CREATE_USER
FROM ORDER_PROCESS.ORDER_BASE.T_INVOICE;
