CREATE OR REPLACE VIEW BUILD_SIM_BOM.BMATHUB_XFRM.V_COMPRESS_BOM_CORE AS
SELECT ITEM,
    ITEM_CLASS_NM,
    ANCHOR_ITEM_ID,
    BOM_NUM,
    LOC,
    CREATE_DTM,
    CREATE_USER
FROM BUILD_SIM_BOM.BMATHUB_BASE.T_COMPRESS_BOM_CORE;