CREATE OR REPLACE VIEW BUILD_SIM_BOM.BMATHUB_ANALYSIS.V_SIM_BOM AS
SELECT ITEM,
    ITEM_CLASS_NM,
    ANCHOR_ITEM_ID,
    BOM_NUM,
    LOC,
    COMPRESS_BOM_CORE.ITEM_CLASS_NM AS DESCRIP,
FROM BUILD_SIM_BOM.BMATHUB_XFRM.V_COMPRESS_BOM_CORE AS COMPRESS_BOM_CORE;