CREATE OR REPLACE VIEW BUILD_SIM_BOM.BMATHUB_XFRM.V_ORIG_BOM AS
SELECT ORIG_BOM.INPUT_ITEM_ID,
    ORIG_BOM.ITEM_CLASS_NM,
    ORIG_BOM.OUTPUT_ITEM_ID,
    LOCATION.LOCATION_ID AS LOC
FROM BUILD_SIM_BOM.BMATHUB_BASE.T_ORIG_BOM AS ORIG_BOM 
JOIN BUILD_SIM_BOM.BMATHUB_BASE.T_LOCATION_ROOT AS LOCATION
ON  LOCATION.ITEM_ID = ORIG_BOM.INPUT_ITEM_ID
JOIN BUILD_SIM_BOM.BMATHUB_BASE.T_ITEM_DETAIL_ROOT AS ITEM_DETAIL ON ITEM_DETAIL.ITEM_ID = ORIG_BOM.INPUT_ITEM_ID WHERE ITEM_DETAIL.DELETE_IND = 'FALSE';
