PUT file://C:/Users/sakthiannamali.s/Downloads/BOM.csv @BUILD_SIM_BOM."MASTER_DATA".STAGE_LOCATION;

CREATE OR REPLACE FILE FORMAT FORMATE
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER = 1;
    
COPY INTO BUILD_SIM_BOM."MASTER_DATA".ORIG_BOM 
FROM @BUILD_SIM_BOM."MASTER_DATA".STAGE_LOCATION/BOM.csv
FILE_FORMAT = (FORMAT_NAME = 'FORMATE', TYPE = CSV);