CREATE OR REPLACE TABLE BUILD_SIM_BOM.BMATHUB_BASE.T_COMPRESS_BOM_CORE (
    ITEM VARCHAR(21),
    ITEM_CLASS_NM VARCHAR(30),
    ANCHOR_ITEM_ID VARCHAR(21),
    BOM_NUM INTEGER,
    LOC VARCHAR(10),
    CREATE_DTM VARCHAR(31),
    CREATE_USER VARCHAR(10)
);